### ISSUE TITLE
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)

### ISSUE THREAD

**Issue by TaLucGiaHoang** [renesas-rcar/linux-bsp#7]
I met this issue when trying to clone the repository
```
$ git clone https://github.com/renesas-rcar/linux-bsp.git
Cloning into 'linux-bsp'...
remote: Enumerating objects: 9093988, done.
remote: Counting objects: 100% (1003684/1003684), done.
remote: Compressing objects: 100% (216197/216197), done.
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 2978 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

```

**Comment by rOt779kVceSgL** [comment]
I faced the same issue on Ubuntu 20.04 LTS but resolved by cloning at midnight, when network traffic volume is low. Maybe it happens when your network speed is slow.

---

Leaving what I tried here (but didn't work for me):

- Setting buffer size
  - ref. https://qiita.com/bacchus1225/items/d9ec1e2387c2e82d25ba#%E8%A7%A3%E6%B1%BA
```
git config --global http.postBuffer 500M
git config --global http.maxRequestBuffer 100M
git config --global core.compression 0
```
- Upgrading git from 2.25.1 to 2.46.0
```
sudo add-apt-repository -y ppa:git-core/ppa
sudo apt update
sudo apt upgrade
```
- Setting http.version
  - ref. https://support-ja.backlog.com/hc/ja/articles/1500000468922-Git%E3%81%AB%E3%83%97%E3%83%83%E3%82%B7%E3%83%A5%E3%81%A7%E3%81%8D%E3%81%BE%E3%81%9B%E3%82%93  
```
git config --global http.version HTTP/1.1
git config --global http.postBuffer 157286400
```
